### ISSUE TITLE
Personicle event analysis: Metadata API: Add stream tablename to metadata record

### ISSUE THREAD

**Issue by vaibhav-clearsense** [ClearsenseData/backend-data-api-v2#10]

**Comment by vaibhav-clearsense** [comment]
Table name is needed to run the analysis queries

**Comment by tirth-clearsense** [comment]
review [commit](https://github.com/ClearsenseData/backend-data-api-v2/commit/49d3d9faab72bc2bb8daffd713750e631042080d)
this update returns the table name in the response of metadata/datastream endpoint
